### PR TITLE
Added possibility to get messages just from subscribed topics

### PR DESCRIPTION
**Pull request by vincenzodibiaggio**

### CODE REVIEW

**Comment by karpy47** [comment]
Thanks for contributing. 
In this case it feels to me like this functionality should rather be handled by the external environment calling the package. Once the program is restarted the variable $subscribedTopics is empty. To remember subscribed topics you would need to store in DB which is outside of this package.
Please enlighten me if I've missed something.

**Comment by vincenzodibiaggio** [comment]
Hi K,
IMHO, if I subscribe specific topics when I fetch messages from the server, the return value should contain only messages from subscribed topics.

**Comment by karpy47** [comment]
Hi there! Well the MQTT server should only return messages of subjects you have subscribed for in the first place (based on the id used when calling the server). If you need to filter messages from certain topics, that is outside of the client I think. Not fetching all messages also creates a stack of messages not acknowledged at the server (if QoS>1) that will be resent after every connect (possibly depending on server behaviour).

**Comment by vincenzodibiaggio** [comment]
Hello!
The beavior described by you is not the same that I have encountered during my tests:

There are 3 topics: /device/SERIAL/ack, /device/SERIAL/status, /device/SERIAL/cmdserial and I have subscribed last two by `sendSubscribe` function. When I have fetched messages with `getPublishMessages` function, the return value contained messages from all topics.

With this beavior, I guess that is better to store subscribed topics to retrieve messages just from these instead all server topics, otherwise I guess that it is unuseful to subscribe specific topics

**Comment by karpy47** [comment]
I see. Could there be some unwanted wildcard involved when subscribing? Servers sometimes have different ways of handling wildcards, eg  /device/Serial/* or just /device/Serial
It does not sound like proper behavior of server to send all topics if you have not subscribed to them. Large servers typically handle loads of topics.

**Comment by vincenzodibiaggio** [comment]
No wildcard in my code, but I don't know server configuration.
So, if you don't like my proposal I'll use it by my fork.

Thanks.

**Comment by karpy47** [comment]
Since your code solves a problem that does not seem to be normal server behavior it seems better to keep it in your fork for now. Thanks anyway.

**Pull request closed without merging**
